# Generated by Django 3.1.2 on 2021-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmark_bookasin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarkStatus',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='bookASIN',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.CharField(max_length=512),
        ),
    ]
