# Generated by Django 3.1.2 on 2021-05-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookmark_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
