# Generated by Django 3.1.2 on 2021-05-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('categoryname', models.CharField(max_length=25)),
                ('categorycount', models.IntegerField(max_length=5)),
            ],
        ),
    ]
