# Generated by Django 3.1.2 on 2021-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorycount',
            field=models.IntegerField(),
        ),
    ]
