# Generated by Django 3.1.2 on 2021-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210521_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcategories',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
