# Generated by Django 3.2.3 on 2021-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcategories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
