# Generated by Django 3.1.2 on 2021-05-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_allcategories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcategories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
